CC = clang
CFLAGS = -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow

inheritance: inheritance.c
	$(CC) $(CFLAGS) -o inheritance inheritance.c

clean:
	rm -f inheritance
